project_name: plow
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
nfpms:
- maintainer: artemtech@github
  description: A high-performance HTTP benchmarking tool with real-time web UI and terminal displaying. Local build based on https://github.com/six-ddc/plow
  homepage: https://github.com/artemtech/plow
  license: Apache-2.0
  formats:
  - deb
  - rpm
  - apk

